### ISSUE TITLE
Prompts to get data end with a statement like "Action: I will parse the JSON and extract..." but the action isn't done?

### ISSUE THREAD

**Issue by AlanSl** [nearform/langchain-google-calendar#13]
If I create some events, and I do a prompt like:

> What are my events today?

...it ends with an output like this:

> [chain/end] [1:chain:agent_executor] [18.62s] Exiting Chain run with output: {
>   "output": "I have successfully retrieved the events for today. I should parse the JSON and extract the relevant information.\nAction: I will parse the JSON and extract the title, start time, and end time for each event."
> }
> {
>   result: {
>     output: 'I have successfully retrieved the events for today. I should parse the JSON and extract the relevant information.\n' +
>       'Action: I will parse the JSON and extract the title, start time, and end time for each event.'
>   }
> }

It doesn't seem to actually do the action, although it seems like it should be well within its capabilities. Earlier on in the output, there is appropriate JSON content about the events; it has all the data the action text talks about (albeit with different key names):

> [tool/start] [1:chain:agent_executor > 4:tool:google_calendar] Entering Tool run with input: "display meetings for today"
> Detected classification:  view_events
> [tool/end] [1:chain:agent_executor > 4:tool:google_calendar] [9.33s] Exiting Tool run with output: "Events in JSON format: 
> [
>   {
>     "id": "6fjfm5rnamiuggenn5nruhbi7o",
>     "status": "confirmed",
>     "summary": "Walk the dog",
>     "start": {
>       "dateTime": "2023-05-30T14:00:00+01:00",
>       "timeZone": "Europe/London"
>     },
>     "end": {
>       "dateTime": "2023-05-30T15:00:00+01:00",
>       "timeZone": "Europe/London"
>     }
>   }
> ]"
> [chain/start] [1:chain:agent_executor > 5:chain:llm_chain] Entering Chain run with input: {
>   "input": "What are my meetings today?",
>   "agent_scratchpad": "This was your previous work (but I haven't seen any of it! I only see what you return as final answer):\nThought: I should use the `google_calendar` tool to retrieve the meetings for today.\nAction:\n```\n{\n  \"action\": \"google_calendar\",\n  \"action_input\": \"display meetings for today\"\n}\n```\n\nObservation: Events in JSON format: \n[\n  {\n    \"id\": \"6fjfm5rnamiuggenn5nruhbi7o\",\n    \"status\": \"confirmed\",\n    \"summary\": \"Walk the dog\",\n    \"start\": {\n      \"dateTime\": \"2023-05-30T14:00:00+01:00\",\n      \"timeZone\": \"Europe/London\"\n    },\n    \"end\": {\n      \"dateTime\": \"2023-05-30T15:00:00+01:00\",\n      \"timeZone\": \"Europe/London\"\n    }\n  }\n]\nThought:",
>   "stop": [
>     "Observation:"
>   ]
> }

This happens pretty consistently for "view" type prompts. I don't think it's a problem with my setup as it can create events just fine.

Here's a file with the full output for a prompt in case its a "just me" thing:

[langchain-get-output.md](https://github.com/nearform/langchain-google-calendar/files/11599368/langchain-get-output.md)

**Comment by andrejstas** [comment]
Thanks for raising this issue, I also noticed this behaviour and was not able to fix it yet.
