### ISSUE TITLE
Should the tool be able to send invites / add guest?

### ISSUE THREAD

**Issue by AlanSl** [nearform/langchain-google-calendar#25]
In my testing (https://github.com/nearform/langchain-google-calendar/issues/18), it seems that neither this tool nor Google Assistant can create calendar events with guests. Adding prompts including guests seems to always result in appending guest details to titles (and sometimes description content) but seems to never result in actual guests being added or invites sent.

Is this something we'd want this tool to be capable of? If it isn't, should we explicitly advise / document that this is something we don't support?

My gut feeling is that this would be an important feature for real-world usage but also, we'd want to add some sort of confirmation step to avoid invites being sent incorrectly.

**Comment by andrejstas** [comment]
It was not part of the scope at the moment, though I agree that for real-world usage it would be an important feature to have.
